server:
  port: 7002

spring:
  application:
    name: eureka-client-coupon-distribution
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: FrankCouponHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000
  kafka:
    bootstrap-servers:
      -127.0.0.1:9092
    consumer:
      group-id: frank-coupon-x
      auto-offset-reset: latest #从最后一条消费
  #开启ribbon重试机制，即获取服务失败是否从另一个节点重试
  cloud:
    loadbalancer:
      retry:
        enabled: true

#服务启动后，向此地址注册服务
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/


logging:
  level:
   com.frank.coupon: debug


#feign配置
feign:
  hystrix:
    enabled: true #默认关闭
  client:
    config: # global config
      default:
        connectTimeouot: 20000 #default is 10s
        readTimeout: 5000
      eureka-client-coupon-template: #specifc config
        connectTimeouot: 30000 #default is 10s
        readTimeout: 5000