server:
  port: 7001
#  servlet:
#    context-path: /coupon-template

spring:
  application:
    name: eureka-client-coupon-template
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: FrankCouponHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

# --------------------------
info:
  app:
   name: frank-coupon-template
   groupId: frank-coupon-service
   artifactId: coupon-template
   version: 1.0-SNAPSHOT
# --------------------------

logging:
  level:
   com.frank.coupon: debug